/* Generated by Makefile.win32.features-h.  Do not edit. */
#ifndef CAIRO_FEATURES_H
#define CAIRO_FEATURES_H 1
#define CAIRO_HAS_WIN32_SURFACE 1
#define CAIRO_HAS_WIN32_FONT 0
#define CAIRO_HAS_FT_FONT 1
#define CAIRO_HAS_IMAGE_SURFACE 1
#define DISABLE_SOME_FLOATING_POINT 1
#endif
